### ISSUE TITLE
[Suggestions] Some details that could be useful

### ISSUE THREAD

**Issue by ThAsviix24** [Linus4/csgoverview#1]
First of all, very good program, finding clips is really easy with this tool, I love it!
But sometimes finding myself is pretty hard so I had some suggestions to improve it.

- Show to current round number
- Select time for killfeed to disapear
It would really make things a lot easier !
Thanks in a advance if you can consider these ideas !

**Comment by Asviix** [comment]
I'm not familliar with GO but I'll try to do it myself, I'll come back here if I run into issues.

**Comment by Linus4** [comment]
Thanks, I'm glad the program is useful to you :) These are some great suggestions - here is how I would implement them (I'm busy with uni atm, but I will get around to it):

* add the current round number to the window title (https://github.com/Linus4/csgoverview/blob/d4b26454133e1eb5e0ea083ae4967ed3966410a9/app.go#L327) . This would be the quickest and easiest way to get this done for now.
* add a new variable to the default config (https://github.com/Linus4/csgoverview/blob/d4b26454133e1eb5e0ea083ae4967ed3966410a9/app.go#L48) and add the corresponding flags in main_(linux,windows).go respectively. [This](https://github.com/Linus4/csgoverview/blob/d4b26454133e1eb5e0ea083ae4967ed3966410a9/match/match.go#L21) is the field containing the time for the killfeed to disappear. It would probably have to be turned into a `var` and be set in the NewMatch function.

**Comment by ThAsviix24** [comment]
Cool !
I'll look into it and will do a pull request if I can get something done :D

**Comment by ThAsviix24** [comment]
Just a question @Linus4, How do you build the program ?
I don't really work with Go

**Comment by Linus4** [comment]
Assuming you're on linux:

[Here's](https://github.com/Linus4/csgoverview#linux-installation) what you need to do: 

1. Install dependencies
2. clone this repo
3. cd into it
4. go build

If you're on windows, it will take quite some time to set up all those sdl libraries etc. That's why I'm just using linux for development for this project.

**Comment by ThAsviix24** [comment]
I got a Rasbperry Pie, I'll take a look at that, or building it in a VM would work right ?

**Comment by Linus4** [comment]
Both options should be fine.

**Comment by Linus4** [comment]
I added the current round number to the title bar in a62114c460ed7833d57ddc94917ab1f58a0292cc.

**Comment by ThAsviix24** [comment]
Thanks a lot !
It's a really good program keep up the good work !
