### ISSUE TITLE
Embedding support?

### ISSUE THREAD

**Issue by pinpox** [Linus4/csgoverview#11]
Hi, just a quick question:
I'm building a webapp that let's my csgo group view stats about the last matches we played. (For now the demo files are uploaded manually to the server). 

I would like to have a demo viewer on the page
Is there any way I could embed a 2D demo player in a html page?

**Comment by Linus4** [comment]
Hi @pinpox , as far as I know there is no straightforward way to do that as csgoverview uses SDL2. Maybe you can use [emscripten](https://emscripten.org/) or another project like that (for golang) to compile the app to WebAssembly.

Your project sounds really interesting, though! :-)
