### ISSUE TITLE
Players sometimes displayed on the wrong "floor" 

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#12]
On Vertigo, some areas are considered the "top floor" when they shouldn't be. Scaffolding on A Ramp is one example, another is stairs on B where jumping or getting on any of the boxes shows you on the floor above.

Here you can see the T appearing as if he's on the floor above, while being bottom of scaffolding
![onxe2ZaRwq](https://user-images.githubusercontent.com/22244672/94715056-57feff00-0323-11eb-8d50-298743d3f3d5.gif)

And here's an example towards B
![bTWufRN3k1](https://user-images.githubusercontent.com/22244672/94715802-5aae2400-0324-11eb-8fba-597cbf92fd98.gif)

Here's an example on mirage: Underpass looks like Catwalk
![image](https://user-images.githubusercontent.com/22244672/94883927-524c0b00-0442-11eb-9394-66510678f5ba.png)
Even though mirage does not have two "floors", it's still a little confusing

**Comment by Linus4** [comment]
Hi @langhillie !

I use the player's position along the z-axis to determine whether a player is on normal elevation. See [this line in common.go](https://github.com/Linus4/csgoverview/blob/844cdb04aacfd0f0cf45c495fe67d29aa4faae5f/common/common.go#L134).

So, I *could* adjust the threshold where normal elevation starts. On Vertigo, I chose the threshold to align with the A ramp / short bridge area. This is a very simple best-effort approach that will inevitably lead to problems on maps with different elevation levels.

I think it's possible to fix the issue on Mirage, though. Thanks for bringing this to my attention.

**Comment by Linus4** [comment]
fixed by 17bd062c6762c4301920989b142318f20f6cb8ec
