### ISSUE TITLE
Smoke team indicators

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#15]
Currently once a smoke is down there's no way to tell which team threw it, so you have go skip back a few times to find out.

The way other 2D demo viewers do it is just drawing the outline of the smoke in the colour of the throwing team.

**Comment by Linus4** [comment]
I like this idea!

The `Effect` type ([here](https://github.com/Linus4/csgoverview/blob/master/common/common.go#L35)) would have to expanded by adding a field with type `demoinfo.Team`. 
[This](https://github.com/Linus4/csgoverview/blob/844cdb04aacfd0f0cf45c495fe67d29aa4faae5f/match/match.go#L206) is the function in the parser where the field would have to be added for parsing.
[This](https://github.com/Linus4/csgoverview/blob/844cdb04aacfd0f0cf45c495fe67d29aa4faae5f/draw.go#L149) is the function that draws grenade effects. I would pick a very light version of the normal team color for the outline.

**Comment by Linus4** [comment]
Added with #19
