### ISSUE TITLE
Players not accurately being shown as "full white"

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#17]
Right now (I believe, according to the code I skimmed), players are only shown as "full white" when they have 3.1 seconds of flash remaining, but in game, your screen is full white until there is ~2 seconds remaining, so players are not displayed as full white when they should be.

**Comment by Linus4** [comment]
I used a plugin called [practice mode](https://github.com/splewis/csgo-practice-mode/) to figure this value out. At 3.1 seconds I was 100 % blind; with less than that I could see a few shapes of my surroundings. Maybe these were still images from when the flash went off, though. My idea was that players should only be displayed as full white when they have literally no visibility. I'll look into it.

**Comment by langhillie** [comment]
Actually you're right, I went back and tested and 3.1 seconds is correct. Not sure why I thought it was 2
