### ISSUE TITLE
Finer control over demo playback speed

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#18]
With 2d demos it's usually nice to go a bit faster than 1x speed, however currently the only option bumps playback up to 5x which is a little fast. 5x is useful, but it would be nice to have the ability to watch at 1.5x or 2x speed.

Maybe tapping w could instead increase playback speed by 0.5x at a time? Or double the previous speed (2x, 4x, 8x, etc)?

**Comment by Linus4** [comment]
Or add shift-w and shift-s for x0.25 and x2.0 ?

**Comment by langhillie** [comment]
That would be a step in the right direction at least, but I do think having finer control - being able to go 1.5x, 2x, 2.5x, etc would be useful. 

In my case at least, when I used an alternative 2d demo viewer I would frequently jump between 1.25x, 1.5x, and 2x.

**Comment by Linus4** [comment]
Hey, I've created a PR #31 for this issue and I'd appreciate your feedback @langhillie :)

**Comment by langhillie** [comment]
Yo, I'll take a look at this tonight
