### ISSUE TITLE
Update map overview file for de_dust2

### ISSUE THREAD

**Issue by TheKrunch** [Linus4/csgoverview#24]
**Describe the bug**
The current dust2 map overview is using the old map with B site doors flipped.

**To Reproduce**
1. Load a dust2 demo
2. See b site doors are flipped

**Expected behavior**
To have the correct map overview.

I see that you talk about a different repo in this link: https://github.com/Linus4/csgoverview/wiki/Overview-Images.
So this issue might not even be on your end/I can fix it myself. I just thought you should be made aware!

**Comment by Linus4** [comment]
Hi, thanks for bringing this to my attention. I was hoping the maintainer of this other repo would update the overviews, but then I forgot about it. Luckily his script still works, so I could extract the new version of de_dust2. You can put the image below in your `csgoverview/assets/maps` directory and replace the old one.

![de_dust2](https://user-images.githubusercontent.com/20419033/105245545-4f506400-5b72-11eb-8fa7-31a95f34ed76.jpg)

I will include this in the next release of csgoverview and file a PR for the overviews repo.

**Comment by Linus4** [comment]
The original repo was updated., so the csgoverview installer will fetch the images from there for new installations.
