### ISSUE TITLE
Hiding team names

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#27]
Currently for scrim/league demos off of ESEA, team names are displayed for every player, causing their igns to be cut off. I'm not sure if it would be feasible, but it would be nice if team names could be hidden so full player names could be shown. Example:
![VirtualBoxVM_6uGwFl8sAH](https://user-images.githubusercontent.com/22244672/107153314-394cec80-6943-11eb-8ab1-a0b707948665.png)

**Comment by Linus4** [comment]
Check this out:  https://github.com/Linus4/csgoverview/pull/28

https://github.com/Linus4/csgoverview/tree/27-hiding-team-names

Does it work for you? I tested with a couple of demos.
