### ISSUE TITLE
Add pause symbol

### ISSUE THREAD

**Issue by Linus4** [Linus4/csgoverview#38]
There should be a symbol in the timer area indicating if playback is paused.

**Comment by augustoccesar** [comment]
I guess if you gonna use the approach of using characters from `DejaVuSans`, these could be useful 😄 

1426 | 2016 | 2161 | 2225 | 2023
:--:|:--:|:--:|:--:|:--:
![Screenshot 2021-04-07 at 14 17 17](https://user-images.githubusercontent.com/5747313/113865526-794a1780-97ac-11eb-9588-5141ca887623.png) | ![Screenshot 2021-04-07 at 14 18 07](https://user-images.githubusercontent.com/5747313/113865551-81a25280-97ac-11eb-93c8-d51100ecaf8f.png) | ![Screenshot 2021-04-07 at 14 18 45](https://user-images.githubusercontent.com/5747313/113865561-8404ac80-97ac-11eb-8c46-75d55b842341.png) | ![Screenshot 2021-04-07 at 14 19 01](https://user-images.githubusercontent.com/5747313/113865569-85ce7000-97ac-11eb-9809-68fe87ed0c29.png) | ![Screenshot 2021-04-07 at 14 17 46](https://user-images.githubusercontent.com/5747313/113865540-7cdd9e80-97ac-11eb-9efb-4b7369413803.png)

**Comment by Linus4** [comment]
That was fast :D And yes, these are exactly what I was looking for :P Thanks!
